name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake
        uses: Platane/snk@v3
        with:
          github_user_name: phdantass
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publicar snake.svg na branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
